### PR TITLE
Added a more robust monit check that looks for response from riak-cs ping endpoint

### PR DESCRIPTION
**Pull request by rickfarmer**
Currently, it is possible under several circumstances (e.g. disk capacity is maxed out) for the Riak-CS pid file to exist even when the process has stopped or stopped responding. As such, monit will not attempt a restart if the pid file exists. We have added a secondary monit failure check to verify that the riak-cs heartbeat endpoint at "/riak-cs/ping" is also responding. If not, monit with detect the failure condition and restart the riak-cs process.

### CODE REVIEW

**Comment by ljfranklin** [comment]
@rickfarmer Can you provide some examples of what would cause the pid file to exist when riak-cs has stopped?

It seems logical to auto-restart when riak-cs is no longer responding, but are you sure we want to restart every time the ping fails? Is monit going to ping while riak-cs is starting, or does it avoid checking while a start/stop/restart is happening? 

Is ping reliable enough that we know we need to restart the first time a ping fails? If not, monit has the ability to wait for multiple failures, with `for 3 cycles` or `for 3 times within 5 cycles`. 

If we had some specific examples we could better decide what kinds of conditions to use. We also need to know how to test that this change does what you need it to do.

**Comment by ljfranklin** [comment]
We learned a bit more about how monit works and have confirmed that the the `if failed` clause only happens when the pid file exists. So as long as we don't write the pid file until riak-cs is pingable this should work as advertised.

There is still a question of whether we want to see more than one failure before restarting. It just comes down to responsiveness of restarting vs defensiveness against spurious failures (which we haven't observed and don't expect).

We still need a case to test against, either way.

**Comment by rickfarmer** [comment]
That’s great, Lyle.

Currently this release is using a Riak-CS version (1.4.x) with a known bug that doesn’t restart when the process dies.  This is corrected in Riak-CS 1.5.x.  We can tell that the service is unavailable because the ping endpoint in unresponsive.  Unfortunately, only restating the process will make the service available again.

I would be glad to help with building a test case.  How do should I approach testing this against monit?

On April 3, 2015 at 11:18:32 AM, Lyle Franklin (notifications@github.com) wrote:

We learned a bit more about how monit works and have confirmed that the the if failed clause only happens when the pid file exists. So as long as we don't write the pid file until riak-cs is pingable this should work as advertised.

There is still a question of whether we want to see more than one failure before restarting. It just comes down to responsiveness of restarting vs defensiveness against spurious failures (which we haven't observed and don't expect).

We still need a case to test against, either way.

**Comment by robdimsdale** [comment]
I agree it's difficult to create a test case; I think we're just interested in some steps to be able to validate your desired behavior. They can be manual steps.

Also, the current final release (v9) uses Riak-CS 1.5.4 and Riak 1.4.12 - is the issue you mention fixed in this release?

**Comment by rickfarmer** [comment]
That’s great info, Rob.

When do we expect v9 to be released?

The test I used when verifying the functionality was to use vagrant to spin up an instance of nginx with the same failure code, killed the nginx service leaving the pid file intact, then watched as monit tested the ping endpoint then restarted nginx.  

Would you like me to send over what I have or do you want me to build a vagrant config for Riak-CS to do the same?

Thanks,
Rick

On April 6, 2015 at 4:07:24 PM, Rob Dimsdale (notifications@github.com) wrote:

I agree it's difficult to create a test case; I think we're just interested in some steps to be able to validate your desired behavior. They can be manual steps.

Also, the current final release (v9) uses Riak-CS 1.5.4 and Riak 1.4.12 - is the issue you mention fixed in this release?

**Comment by robdimsdale** [comment]
V9 was released a couple of weeks ago - about a week before you opened this PR, so it's possible you're already using that.

I'm not sure that you need to send what you have or build a vagrant config for Riak-CS. It sounds like we  could test this by ssh-ing onto the Riak-CS VM and `kill -9` the Riak-CS process; without this PR Riak-CS should stay dead, and with the PR it should be restarted by monit.

We were under the impression that under the above use case monit would observe the pid-file is stale and restart the process. We'll try investigate why monit isn't behaving how we expect, and whether this can be fixed a different way. If not, we'll merge this PR

**Comment by bobhlo** [comment]
Any thoughts/progress?

**Comment by karlkfi** [comment]
@rickfarmer Let us know if upgrading to v9 does or doesn't fix your issue. If it doesn't, we can re-evaluate merging this PR.

@bobhlo Are you seeing this issue as well?

**Comment by karlkfi** [comment]
We've run the following test on the latest version of cf-riak-cs-release:

1. watch -n1 curl http://10.244.3.6:8080/riak-cs/ping
1. ssh into a riak-cs vm
1. kill -9 $(cat /var/vcap/sys/run/riak-cs/riak-cs.pid)

When the process is killed, the curl returns "Connection refused" and then quickly begins responding again.

Note: `curl http://localhost:8080/riak-cs/ping` always returns "Connection refused" when ssh'd into the riak-cs vm, tho we're not sure why. Curling with the explicit IP seems to work. This seems to indicate that the proposed change would also fail. Did you ever see it working?

**Comment by menicosia** [comment]
Hi @rickfarmer,

The steps you gave didn't seem to work, and the corner case you're solving only seems to be in the case of catastrophic failure.

We haven't heard back from you in a while, so this is going to miss the next release of riak-cs; is it important that we look at this for the next release, or should we abandon these changes...?

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by rickfarmer** [comment]
Hi Marco,

I agree with you.  This was an edge case, but catastrophic.  I'm going to ask Sean to make the call on whether we should refine this solution or abandon it.

Hi Sean,

Please review and provide direction.

Thanks,
Rick

**Comment by robdimsdale** [comment]
Closing this as it has been open over a year without response.

**Pull request closed without merging**
