### PR TITLE
Allow seeded_buckets to be specified in templates

### PR DESCRIPTION
**Pull request by rkoster**
Same as https://github.com/cloudfoundry/cf-riak-cs-release/pull/26 but now at with correct target branch.

### CODE REVIEW

**Comment by karlkfi** [comment]
@rkoster Can you explain why you need `seeded_buckets` in the spiff deployment manifest templates?

As far as we can tell, seeding buckets is only useful when deploying riak-cs without a service-broker. Since the templates are primarily for creating a deployment manifest for use with CloudFoundry, a broker is provided. 

Do you have a use case where you need both seeded buckets AND a service-broker?
If not, how are you using the templates?

We're a little worried that adding this to the templates (which are frequently used by first-time users) will confuse more people than it helps.

**Comment by rkoster** [comment]
I'm using `seeded_buckets` to create buckets for the [internal Cloud Foundry blobstore](https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-properties.yml#L113). But I found that just giving the specifying the admin credentials also works since the cloud_controller_ng will create the buckets when they don't exist. There however is the problem of a circular dependency between the deployments since riak-cs requires the gorouter and the cloud_controller needs riak-cs.

**Comment by karlkfi** [comment]
There's a conceptual dependency cycle between the two bosh releases (cf-release & cf-riak-cs-release), but the internal components don't have a dependency cycle. 

- riak-cs, cloud_controller and gorouter all depend on NATS for communication.
- apps and cloud_controller depend on gorouter to route to riak-cs

This is still strictly linear, because riak-cs itself does not depend on any of the components that depend on it.

The only potential cycle I can think of would be if you are spiffing together manifest templates and want to only put the admin credentials in one place. The normal pattern for this is to extract the credentials out to another location and have both templates depend on that stub.

Since bucket seeding only gives the admin user access to the bucket, you have to give cloud_controller the admin credentials anyway. 

So it sounds like you don't actually need this PR for your use case. Is that right?

**Comment by karlkfi** [comment]
@robdimsdale mentioned that there might be a dependency cycle if riak-cs and cf-release are in two different deployments and the cloud_controller needs to use the blobstore during the deploy phase (rather than just at runtime). In that case, the cf-release deployment wouldn't finish deploying unless deployed at the same time as cf-riak-cs-release. The obvious way around that would be to make them part of the same deployment. However, I'm not sure such a deploy-time dependency exists.

**Comment by karlkfi** [comment]
After talking to the runtime team, it sounds like cloud_controller probably doesn't have an explicit deploy-time dependency on the blobstore, BUT the deploy does kick of async tasks to upload the buildpacks to the blobstore (configured in the deployment manifest). These upload tasks would probably fail if the blobstore isn't available. The upload seems to be retried a few times, but would likely fail before a synchronous riak-cs deploy would finish. So even if cloud_controller comes up, you would have to manually reupload the buildpacks (or somehow re-enqueue the upload tasks).

Note: The above was determined by currsory exploration of the cloud_controller code, not actual experimentation. YMMV.

**Comment by rkoster** [comment]
Indeed this PR is not required for my usecase, since the cloud_controller can create the buckets by it self when given admin_credentials. From a separation of concerns point of view it would be nice it bucket seeding could be extended to allow seeding of user bucket pairs.

@robdimsdale is right I'm indeed deploying it as 2 separate deployments (cf and riak-cs). I have however not experienced the issue because cf was first deployed with nfs. After that I deployed riak-cs. And then switch from nfs to riak-cs for the blobstore.

But thanks for the heads up will keep it in mind when rebuilding the environment.

**Comment by karlkfi** [comment]
Yeah, if you deployed cf-release with a different blobstore and then reconfigured it, that would work. You might have to manually upload the buildpacks to the new blobstore tho, not sure.

I do agree that if we have bucket seeding by name it'd make sense to also have ACL initialization for those buckets, but it's not high priority for us to add, since it's an edge case most CF users won't need to use.

**Pull request merged**
